# Form implementation generated from reading ui file 'five_numbers.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_game(object):
    def setupUi(self, game):
        game.setObjectName("game")
        game.resize(800, 600)
        game.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=game)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.information = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.information.setGeometry(QtCore.QRect(70, 210, 641, 191))
        self.information.setStyleSheet("background-color: rgb(170, 255, 255);\n"
                                       "border-color: rgb(255, 255, 255);\n"
                                       "")
        self.information.setReadOnly(True)
        self.information.setObjectName("information")
        self.Exit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Exit.setGeometry(QtCore.QRect(644, 493, 81, 31))
        self.Exit.setStyleSheet("background-color: rgb(14, 46, 255);\n"
                                "color: rgb(255, 255, 255);")
        self.Exit.setObjectName("Exit")
        self.start = QtWidgets.QPushButton(parent=self.centralwidget)
        self.start.setGeometry(QtCore.QRect(70, 493, 91, 31))
        self.start.setStyleSheet("color: rgb(255, 255, 255);\n"
                                 "background-color: rgb(7, 44, 255);")
        self.start.setObjectName("start")
        self.answer = QtWidgets.QPushButton(parent=self.centralwidget)
        self.answer.setGeometry(QtCore.QRect(640, 180, 75, 24))
        self.answer.setStyleSheet("color: rgb(255, 255, 255);\n"
                                  "background-color: rgb(20, 3, 255);")
        self.answer.setObjectName("answer")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(70, 30, 641, 141))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.text = QtWidgets.QTextEdit(parent=self.widget)
        self.text.setReadOnly(True)
        self.text.setObjectName("text")
        self.verticalLayout.addWidget(self.text)
        self.writing_numbers = QtWidgets.QTextEdit(parent=self.widget)
        self.writing_numbers.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.writing_numbers.setObjectName("writing_numbers")
        self.verticalLayout.addWidget(self.writing_numbers)
        game.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=game)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 33))
        self.menubar.setObjectName("menubar")
        game.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=game)
        self.statusbar.setObjectName("statusbar")
        game.setStatusBar(self.statusbar)

        self.retranslateUi(game)
        QtCore.QMetaObject.connectSlotsByName(game)

    def retranslateUi(self, game):
        _translate = QtCore.QCoreApplication.translate
        game.setWindowTitle(_translate("game", "MainWindow"))
        self.information.setHtml(_translate("game",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "hr { height: 1px; border-width: 0; }\n"
                                            "li.unchecked::marker { content: \"\\2610\"; }\n"
                                            "li.checked::marker { content: \"\\2612\"; }\n"
                                            "</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Exit.setText(_translate("game", "Назад"))
        self.start.setText(_translate("game", "Начать"))
        self.answer.setText(_translate("game", "Ответить"))
        self.text.setHtml(_translate("game",
                                     "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                     "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
                                     "p, li { white-space: pre-wrap; }\n"
                                     "hr { height: 1px; border-width: 0; }\n"
                                     "li.unchecked::marker { content: \"\\2610\"; }\n"
                                     "li.checked::marker { content: \"\\2612\"; }\n"
                                     "</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                     "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
                                     "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:700;\">Введите числа</span></p></body></html>"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    game = QtWidgets.QMainWindow()
    ui = Ui_game()
    ui.setupUi(game)
    game.show()
    sys.exit(app.exec())
